
export const getRandomPhrase = (phrases: string[]): string => phrases[Math.floor(Math.random() * phrases.length)];

export const QUIERO_PHRASES = [
  "¡Quiero! A ver esas cartas.",
  "¡Dale, quiero! No te achiques ahora.",
  "Acepto. ¡Quiero!",
  "¡Quiero, y que sea lo que el mazo quiera!",
  "¡Claro que quiero! Venga.",
  "Me la juego. ¡Quiero!",
  "Veamos... ¡Sí, quiero!",
  "Sí, quiero. Sin miedo.",
  "Va pa' delante. ¡Quiero!",
  "Aceptado... ¡Quiero!",
];

export const NO_QUIERO_PHRASES = [
  "Me voy al mazo, que hoy no es mi día de gloria.",
  "Al mazo con todo, que la suerte me dio la espalda.",
  "Prefiero el mazo antes que perder con estilo.",
  "Me retiro al mazo, salvando lo poco que queda de mi orgullo.",
  "Al mazo, que tus cartas me acobardan.",
  "Hasta aquí mi aventura, directo al mazo.",
  "Me voy al mazo, pero vuelvo por revancha.",
  "El mazo me llama, y yo le hago caso.",
  "Al mazo con humildad, que no soy tonto.",
  "Me rindo al mazo, que la baraja me traicionó.",
  "Directo al mazo, que esto no pinta bien.",
  "Al mazo, salvemos el pellejo para la próxima.",
  "Me voy al mazo, pero mi ego se queda a pelear.",
  "El mazo es mi refugio, por hoy.",
  "Al mazo con gracia, que no soy de los que insisten.",
  "Me retiro al mazo, que la fortuna es ciega.",
  "Al mazo, que tus ojos me dicen que vas en serio.",
  "Hasta el mazo, que mejor prevenir que curar.",
  "Me voy al mazo, pero anoto tu cara para la revancha.",
  "El mazo me abraza, y yo lo acepto.",
  "Al mazo con estilo, que soy un gentleman.",
  "Me rindo al mazo, que las cartas no mienten.",
  "Directo al mazo, que hoy no fluye.",
  "Al mazo, que prefiero dormir tranquilo.",
  "Me voy al mazo, pero mi alma de jugador sigue viva.",
  "El mazo es sabio, y yo lo escucho.",
  "Al mazo con resignación, que hay días y días.",
  "Hasta aquí, al mazo sin remordimientos.",
  "Me retiro al mazo, que la vida es corta para malas manos.",
  "Al mazo, que tus sonrisas me delatan.",
  "Me voy al mazo, pero prometo volver más fuerte.",
  "El mazo me espera, y yo no lo defraudo.",
  "Al mazo con humor, que no todo es tragedia.",
  "Directo al mazo, salvando fichas para mañana.",
  "Me rindo al mazo, que la intuición no falla.",
  "Al mazo, que mejor que quedarme en ridículo.",
  "Hasta el mazo, con la cabeza en alto.",
  "Me voy al mazo, que las cartas hablan solas.",
  "El mazo es mi amigo fiel en momentos así.",
  "Al mazo con elegancia, que soy un experto.",
  "Me retiro al mazo, pero mi estrategia brilla en la sombra.",
  "Al mazo, que hoy la diosa fortuna está de vacaciones.",
  "Directo al mazo, que no soy de los que forcejean.",
  "Me voy al mazo, pero te vigilo de cerca.",
  "El mazo me consuela, y yo lo agradezco.",
  "Al mazo con picardía, que hay más rondas.",
  "Hasta aquí mi apuesta, al mazo sin drama.",
  "Me rindo al mazo, que el instinto manda.",
  "Al mazo, prefiriendo la paz a la guerra perdida.",
  "Me voy al mazo, pero esta noche sueño con ases.",
];

export const ENVIDO_WIN_PHRASES = [
  "Mis puntos son ley.",
  "Te gané el tanto.",
  "¡Gané el envido! Sumando...",
  "Estos puntos son míos.",
  "Mejor suerte para la próxima con el envido.",
];

export const ENVIDO_LOSE_PHRASES = [
  "Son buenas. Bien jugado.",
  "Tus puntos son mejores. Te felicito.",
  "Son buenas. Me ganaste el tanto.",
  "Reconozco, son buenas.",
  "Me ganaste bien. Son buenas.",
];

export const TRICK_WIN_PHRASES = [
  "¡Esta mano es mía!",
  "¡Así se juega!",
  "Un paso más cerca de la victoria.",
  "Gano esta mano.",
  "¡Tomá! Para que aprendas.",
];

export const TRICK_LOSE_PHRASES = [
  "Bien jugado.",
  "Me la ganaste.",
  "Buena carta.",
  "Esta es tuya, pero la ronda no terminó.",
  "Mmm, no esperaba esa.",
];

export const FLOR_PHRASES = [
  "Contra el resto, flor me achico. ¡Flor!",
  "El jardín de mi mano ha florecido. ¡Tengo flor!",
  "Perfume de victoria en el aire... ¡Flor!",
  "Con estas tres del mismo palo, digo ¡Flor!",
  "No es suerte, es botánica. ¡Flor!",
  "Linda se te ha puesto la cosa... para mí. ¡Flor!",
  "Tres del mismo color, ¡qué primor! ¡Flor!",
];

export const ENVIDO_PRIMERO_PHRASES = [
  "¡Momento! El envido está primero.",
  "Frená el carro... primero el envido.",
  "Un segundito, que los tantos valen. Envido primero.",
  "No tan rápido. Antes de la guerra, los puntos. Envido primero.",
  "Primero lo primero... ¡y el envido está primero!",
];

export const POST_ENVIDO_TRUCO_REMINDER_PHRASES = [
  "Bueno, resolvimos los tantos. Ahora... ¿qué me decís del truco que te canté?",
  "Listo el envido. Pero te recuerdo que el truco sigue en pie.",
  "Bien, el envido ya pasó. Volvamos a lo importante: ¡TRUCO!",
  "Ya está lo del envido. Ahora a lo que vinimos, ¿aceptás el truco?",
  "Se acabó el envido. Ahora sí, hablemos del truco.",
  "Okay, capítulo cerrado con el envido. ¿Y el truco? Te estoy esperando.",
  "Dejemos los puntos de lado por un momento. Te pregunté... ¿TRUCO?",
];


// Phrases for a standard "Envido" call
export const ENVIDO_PHRASES = [
  "Amalaya con las penas cuando flaquea el corazón, yo le canto envido apenas pues no tengo pa'l rabón.",
  "Atienda la relación que hace un gaucho perseguido: ahorita le vi'a ganar con este grandioso envido.",
  "Aunque lo creas indebido te vi'a cantar un envido.",
  "Aunque yo tenga pintada de computadora, hay un enano aquí metido que me está dele soplar: ¡dale que tenés envido!",
  "El humano me ha herido: dijo que yo no sé jugar al envido.",
  "Vea, vea, vea qué cosa más bonita: salió a afanar envido la famosa Teresita.",
  "Si no me convidas con cerveza, por lo menos ofréceme un envido.",
  "Cuando vine de la Pampa traiba un lazo retorcido, con él enlacé tres cartas, y con dos le digo envido.",
  "A este humano reprimido le vi'a cantar el envido.",
  "A este rival tan bandido le vi'a cantar el envido.",
  "A este humano compungido lo achico con un... envido.",
  "Cuando vine de La Isla traiba un lazo retorcido; con él enlacé dos cartas y con dos le digo envido.",
  "En la quietud de la noche, bajo el cielo estrellado, te canto envido con el corazón enlazado.",
  "Como el río que serpentea, mi envido fluye sereno, y en tus ojos veo el reflejo de un triunfo pequeño.",
  "El envido es como el río, sereno pero profundo, enlaza cartas y almas en un lazo fecundo.",
  "Del espacio exterior, un OVNI trae envido, real que aterriza y al rival lo envide.",
  "Envido con twist: cartas y un poco de twist, real que baila tango en el fist.",
  "Envido ecológico: verde como la pampa, real que recicla tu drama.",
  "El otro día jugaba con el viejo Salvador; vuelta a vuelta envido y truco, ¡pucha, viejo ligador!",
  "Envido y mate: caliente como el desafío, real que quema el desvío.",
  "Envido retro: como un vinilo rayado, real que suena en el faded.",
  "Envido superheroico: capa de espadas, real que salva las jugadas.",
  "Envido galáctico: planetas alineados, dos reales que han girado.",
  "Envido minimalista: menos es más, real que causa el caos.",
  "Envido pop: como un hit de verano, real que baila el humano.",
];

// Phrases for a "Real Envido" call (includes "dos reales")
export const REAL_ENVIDO_PHRASES = [
  "Tenes real envido? Tomala vos, dámela a mí, con real envido te vas a divertir.",
  "Si la computadora te ha aturdido, habrás de perdonarla: es que vino cargada con un esplendoroso real envido.",
  "Qué coraje, qué atrevido: andar comiendo electrones y escupiendo real envido.",
  "Aunque suene presumido yo te canto el real envido.",
  "Un gaucho bajó del cielo en un plato volador, al pasar junto a una vaca, real envido le gritó.",
  "Me llenaste de bronca, ahora el partido te lo gano con real envido y con toda pompa.",
  "Che, humanoide: quedaste tan resentido que hace mucho que no me gritas el real envido.",
  "No sé si arriesgarme tanto... no sé si tengo que tirarme el lance... y bué, te lo digo nomás: ¡real envido!",
  "Parece algo afligido, ¿qué tal si lo sacudo con dos reales envido? ¿Eh?",
  "La pata tiene su pato, la esposa tiene marido, y vos, chitrulo barato, ¿tenés dos reales envido?",
  "Caminando por mis pagos me sorprendió un alarido... yo creí que era Mandinga y no dos reales envido.",
  "Desde el día que he nacido siempre fui un poco fiaca, naides palabra me saca... salvo dos reales envido.",
  "A este truquero atrevido le zampo no uno sino dos reales envido, ¿qué tal?",
  "Estás cansado? ¿Estás molido? Entonces refrescate con dos reales envido.",
  "A ver qué te puedo cantar para no traumatizarte tanto: ¡dos reales envido!",
  "No todo está perdido, seguí mi consejo, acéptame dos reales envido.",
  "Qué me escuches yo te pido, y ahí van... dos reales envido.",
  "No piense en un descuido si no es pa' tanto la cosa... yo le digo real envido que es lo mesmo que olorosa.",
  "Con su boquita de grana y su pelo renegrido, no envidia a la mañana este hermoso real envido.",
  "Quedate tranqui, no es un descuido: te canto real envido, que es puro perfume y buen tino.",
  "Del campo vengo con el lazo, y en la mano traigo un real envido que no falla.",
  "No seas altivo, paisano, que mi real envido te va a bajar los humos.",
  "En la pulpería del sur, con un mate en la mano, te digo: real envido, y que gane el mejor.",
  "Parece algo afligido, ¿qué tal si lo sacudo con dos reales envido?",
  "A mi contrincante aturdido le exclamo: ¡dos reales envido!",
  "A este humano reprimido lo asusto con dos reales envido.",
  "No es descuido ni capricho, es el pulso de la tierra: real envido, aroma puro, que al alma despierta.",
  "Con boquita de grana y pelo renegrido, no envidia a la mañana este hermoso real envido.",
  "En el viento del pampero, llevo mi real envido, un susurro de espadas que al rival lo ha herido.",
  "Dos reales como dos soles en el cielo infinito, envido que ilumina el camino del bandido.",
  "Alarido en la pampa, eco de mi dos reales envido, no es Mandinga, es el grito de un gaucho decidido.",
  "Fiaca en el alma, pero el envido despierta, dos reales que la sangre al rojo fuego alerta.",
  "Aturdido el contrincante, exclamo con eco: dos reales envido, en este duelo de eco.",
  "Reprimido el humano, asusto con dos reales, envido que rompe cadenas, que el miedo desata males.",
  "Real envido, perfume de jazmines en la mañana, no descuido, sino gracia de la pampa temprana.",
  "Dos reales envido, como dos alas de águila, surcan el cielo del truco, invencibles y siglas.",
  "Envido cibernético: bits y cartas en red, real envido que hackea tu dread.",
  "Dos reales como dos pizzas en la noche, envido que sacia el hambre del trote.",
  "Dos reales envido zen: calma en la tormenta, envido que zenifica la tormenta.",
  "Dos reales envido cósmico: estrellas en la mano, envido que conquista el plano.",
  "Real envido quantum: partículas enredadas, envido que salta las barreras guardadas.",
  "Envido filosófico: ¿soy o no soy? Dos reales que resuelven el soy.",
  "Dos reales envido pirata: arrr, tesoro en la mano, envido que hunde el plano.",
  "Real envido floral: pétalos de triunfo, envido que perfuma el lumpio.",
  "Dos reales envido jazz: improvisado y swing, envido que hace ring.",
  "Real envido ancestral: abuelos en el eco, envido que hereda el leco.",
  "Envido surreal: Dalí en las cartas, dos reales que parten.",
  "Dos reales envido legendario: mitos en la mesa, envido que mesa.",
];

// Phrases for a "Falta Envido" call
export const FALTA_ENVIDO_PHRASES = [
  "Pido gancho, gancho pido: ¡chupate esta falta envido!",
  "No todo está perdido, contestá esta falta envido.",
  "Si querés ganarme el partido, quereme esta falta envido.",
  "A este rival comedido lo echo con falta envido.",
  "A este neurótico compungido lo corro con la falta envido.",
  "Sos un adversario dormido, no importa: yo te despierto con un falta envido.",
  "No creas que me has vencido: atájate esta falta envido.",
  "A que te achicas: ¡falta envido!",
  "Para el tanto yo no tengo nada pero vos menos... así que falta envido.",
  "Yo, el computador digo: agarrate fuerte que te mando la falta envido.",
  "Che, humano, no sea tan altivo que yo lo desafío con una falta envido.",
  "No se ponga tan contento por el envite que ha echao, porque escuchará al momento: falta envido, cuñao.",
  "Perdido no está todo, acepta mi falta envido, en la ronda del truco, el honor se ha cumplido.",
  "Queré esta falta envido, si el partido anhelás, en la mesa del destino, el coraje se probás.",
  "Comedido el rival, lo echo con falta envido, en la payada del juego, el trueno ha sonado.",
  "Compungido el neurótico, corro con falta envido, despierto el alma dormida, al desafío encendido.",
  "Dormido adversario, despierto con falta envido, en la noche del truco, el sol ya ha nacido.",
  "Vencido no me ves, ataja esta falta envido, en el lazo de la suerte, el nudo se ha deshecho.",
  "Achicás con mi falta envido, en el aire del desafío, el gaucho no retrocede, el envido es su sino.",
  "Nada tengo pa'l tanto, vos menos aún, falta envido, y el juego se ha inclinado al sur.",
  "Agárrate fuerte, falta envido mando, en el compás de la vida, el truco es mi canto.",
  "Altivo no seas, desafío con falta envido, en la pulpería del alma, el mate se ha enfriado.",
  "Una vez una paloma ofreció darme su nido, y yo creyendo una broma no le eché la falta envido.",
  "Falta envido, cuñao, en el eco de la querencia, el gaucho canta su suerte con firme presencia.",
  "Envidio tu envido, pero el mío es más grande, falta que te deja en el rango.",
  "Falta envido express, como un mate sin azúcar, amargo pero ganador, ¡qué lazo!",
  "Al estilo rap: envido drop, real envido pop, falta que sube el beat non-stop.",
  "Gaucho 2.0: envido app, real envido tap, falta que crashea tu map.",
  "Falta envido gourmet: con chimichurri y pasión, falta que condimenta la acción.",
  "Falta envido light: sin gluten, pero con gluten de coraje.",
  "Falta envido viral: meme que se expande, falta que al rival lo expande.",
  "Falta envido poético: verso que falta, envido que pacta.",
  "Falta envido mágica: abracadabra, falta que abra la bara.",
  "Falta envido épica: saga de naipes, falta que escribe los faipes.",
  "Falta envido cyberpunk: neon en las venas, falta que enciende las cadenas.",
  "Falta envido zen-master: vacío lleno de poder, falta que revela el sed.",
  "Falta envido final: el telón cae, pero el envido queda en la zaga.",
];

export const TRUCO_PHRASES = [
    "¡Truco, che, que con este mazo te mando al revés!",
    "Por el río Paraná navegaba un piojo con un truco en el ojal.",
    "Truco al resto, porque hoy las cartas bailan tango en mi mano.",
    "¡Quiero truco, boludo! Que si no querés, te quedás con el envido solo.",
    "Truco y punto final, como el mate amargo que no se endulza.",
    "Con tres de espada y un ojo en tu cara, ¡truco para ganarte la partida!",
    "Truco, mi viejo, que las estrellas alinearon mi suerte hoy.",
    "¡Truco! Si me lo querés, traé el as de oros o andate a la concha.",
    "Truco con flor, que huelo a victoria desde acá nomás.",
    "Aquí me planto, truco en la voz, porque no hay laburo pero sí cartas.",
    "Truco, retruco no te lo acepto, ¡dale que va o te vas al mazo!",
    "Como el Gaucho Gil, canto truco con el corazón en la espada.",
    "Truco y un abrazo de oso, que te voy a apretar hasta que pidas paz.",
    "¡Truco, carajo! Que con este 7 de oro te limpio el piso.",
    "Truco serio, como el juramento de San Martín en la historia.",
    "Por las pampas vengo, truco en la lengua, victoria en el alma.",
    "Truco al voleo, que si dudás, perdés el turno y el orgullo.",
    "¡Truco, mi amor! Que jugamos por amor o por el doble.",
    "Con un 4 de copas y cara de póker, ¡truco para romperte el esquema!",
    "Truco y mate cocido, caliente como mi mano ganadora.",
    "Soy de Tartagal, truco en la sangre, cristianado en el fuego.",
    "Truco, no seas rata, que las cartas no mienten pero vos sí.",
    "¡Truco! Como el viento pampeano, impredecible y letal.",
    "Truco con envido, que sumo puntos como goles en el clásico.",
    "Pampa, flor y truco agudo, si querés jugar, mostrame el basto.",
    "Truco, boludo, que hoy soy el rey del mazo y vos el peón.",
    "Con un hachazo en el ojo y truco en la boca, ¡avanzá o retrocede!",
    "Truco poético, como versos de Sarmiento en la campaña.",
    "¡Truco al canto! Que si no, te canto la derrota en verso.",
    "Truco y un choripán, jugamos por la birra de la victoria.",
    "Truco serio, che, que la vida es una mano y esta la gano yo.",
    "Como el Paraná que fluye, truco que arrastra tu suerte mala.",
    "¡Truco, faca en mano! No es amenaza, es promesa de puntos.",
    "Truco con risas, que perdés pero te invito al asado después.",
    "Truco y un tango, melancólico pero ganador al final.",
    "Soy pibe del sur, truco en el grito, victoria en el silencio.",
    "Truco, no me mires así, que las cartas ya hablaron por mí.",
    "¡Truco al revés! Que te doy la vuelta como a un guante viejo.",
    "Truco filosófico: ¿querés o no? La duda es el peor envido.",
    "Con dos 4 y un sueño, ¡truco para hacer historia en la mesa!",
    "Truco y un grito al cielo, que Dios me dio esta mano bendita.",
    "Truco cómico, que si perdés, te presto mi mazo para la revancha.",
    "Como el mate redondo, truco que une y separa en un sorbo.",
    "¡Truco, mi reina! Que jugamos por el reino de las cartas.",
    "Truco agresivo: traé lo tuyo o andate llorando al baño.",
    "Truco nostálgico, recordando al viejo que me enseñó a farfear.",
    "¡Truco al toque! Que el tiempo vuela como tu suerte perdida.",
    "Truco y un chiste: ¿por qué el 4 no canta? Porque se va al mazo.",
    "Con el alma de criollo, truco que late como un corazón gaucho.",
    "Truco final, che, que esta mano es mía y la próxima también.",
];

export const RETRUCO_PHRASES = [
    "¡Retruco, la concha! Que con esto te mando a lavar los platos.",
    "Quiero retruco, porque el truco fue suave, ahora va en serio.",
    "Retruco al resto, como el viento que dobla los eucaliptos.",
    "¡Retruco y un abrazo! Que te aprieto hasta que sueltes las cartas.",
    "Retruco con flor, que huelo a revancha desde el otro lado de la mesa.",
    "Quiero retruco, boludo, que si no, te quedás con el punto y la bronca.",
    "Retruco poético, versos que suben la apuesta como el Paraná en crecida.",
    "¡Retruco, carajo! Dos puntos más o te vas al mazo con cola.",
    "Retruco y mate amargo, que endulzar esta mano no se puede.",
    "Quiero retruco, como el gaucho que no se rinde ante el destino.",
    "Retruco serio: las cartas no mienten, pero tu cara sí.",
    "¡Retruco al canto! Que si dudás, perdés el alma y el juego.",
    "Retruco con envido, sumando puntos como goles en tiempo extra.",
    "Quiero retruco, mi viejo, que la vida es una apuesta y yo la sigo.",
    "Retruco cómico: con un 4 de copas, pero cara de basto de oro.",
    "¡Retruco y un tango! Pasión que quema y victoria que arde.",
    "Retruco agresivo: traé el vale cuatro o andate a la mierda.",
    "Quiero retruco, que el truco fue el aperitivo, esto es el plato fuerte.",
    "Retruco nostálgico, recordando al tata que farfeaba en la pulpería.",
    "¡Retruco al voleo! Que el tiempo apura y tu suerte se acaba.",
    "Retruco y un choripán, jugamos por la birra y la gloria.",
    "Quiero retruco, como el sol que sale después de la tormenta.",
    "Retruco filosófico: ¿subís la apuesta o te vas al mazo de los cobardes?",
    "¡Retruco con risas! Perdés, pero te invito al rematch con birra.",
    "Retruco épico: soy el León de la mesa, rugiendo por tres puntos.",
    "Quiero retruco, boludo, que con este mazo te limpio el orgullo.",
    "Retruco y un grito: ¡dale que va, o te vas vos al revés!",
    "¡Retruco al toque! Que las estrellas alinearon mi revancha.",
    "Retruco con un 7 de espada, cortante como navaja en la noche.",
    "Quiero retruco, mi amor, que jugamos por el corazón del juego.",
    "Retruco serio, che, que la derrota duele más que el retruco duele.",
    "¡Retruco y un chiste! ¿Por qué el retruco? Porque el truco fue flojo.",
    "Retruco pampeano, viento que arrastra tu suerte al olvido.",
    "Quiero retruco, como el juramento de lealtad en la campaña.",
    "Retruco y un mate cocido, caliente como mi mano ganadora.",
    "¡Retruco, faca lista! No es amenaza, es el filo de la victoria.",
    "Retruco cómico: con dos 4, pero fe de que gano por cara dura.",
    "Quiero retruco, que el truco fue el comienzo, esto es el clímax.",
    "Retruco nostálgico: al viejo le gustaba subir la apuesta así.",
    "¡Retruco al final! Que esta mano dobla y te deja en cero.",
    "Retruco y un abrazo de oso, apretando hasta que pidas tregua.",
    "Quiero retruco, boludo, que la vida es farfear o rendirse.",
    "Retruco épico: como San Martín cruzando los Andes con cartas.",
    "¡Retruco con flor! Que huelo a tres puntos desde acá.",
    "Retruco agresivo: subí o bajá, pero no me hagas perder tiempo.",
    "Quiero retruco, mi reina, que por vos subo la apuesta al cielo.",
    "Retruco y un tango melancólico, pero ganador al compás.",
    "¡Retruco al revés! Te doy la vuelta como a un guante viejo.",
    "Retruco filosófico: la duda mata, el retruco revive.",
    "Quiero retruco final, che, que esta es la mano que rompe la mesa.",
];

export const VALE_CUATRO_PHRASES = [
    "¡Vale cuatro, la puta madre! Que con esto te limpio el mazo entero.",
    "Quiero vale cuatro, porque tres no alcanza para mi ambición.",
    "Vale cuatro al resto, como el rayo que parte el cielo en dos.",
    "¡Vale cuatro y un grito! Que si no querés, te vas con las manos vacías.",
    "Vale cuatro con basto, que corto tu suerte como navaja afilada.",
    "Quiero vale cuatro, boludo, que cuatro puntos son mi corona.",
    "Vale cuatro poético, versos que cierran la apuesta con gloria.",
    "¡Vale cuatro, carajo! Cuatro o nada, elige o revoleá las cartas.",
    "Vale cuatro y mate quemado, que esta mano arde en victoria.",
    "Quiero vale cuatro, como el gaucho que apuesta el rancho entero.",
    "Vale cuatro serio: las cartas gritan, tu cara calla la derrota.",
    "¡Vale cuatro al canto! Que la duda es el peor no quiero.",
    "Vale cuatro con envido, sumando como el río que inunda la pampa.",
    "Quiero vale cuatro, mi viejo, que la vida es todo o nada.",
    "Vale cuatro cómico: con un 4 solo, pero fe de campeón mundial.",
    "¡Vale cuatro y un tango! Pasión que explota en cuatro puntos.",
    "Vale cuatro agresivo: subí o andate, cobarde de la mesa.",
    "Quiero vale cuatro, que el retruco fue el fuego, esto es la hoguera.",
    "Vale cuatro nostálgico, al tata le gustaba cerrar así la noche.",
    "¡Vale cuatro al toque! Que el destino apura y yo lo agarro.",
    "Vale cuatro y un asado, jugamos por la parrillada eterna.",
    "Quiero vale cuatro, como el sol que brilla en su zenit.",
    "Vale cuatro filosófico: ¿todo por cuatro o nada por miedo?",
    "¡Vale cuatro con risas! Perdés, pero te presto el mazo para venganza.",
    "Vale cuatro épico: soy el emperador de la mesa, coronado en oro.",
    "Quiero vale cuatro, boludo, que con esto te borro del mapa.",
    "Vale cuatro y un rugido: ¡dale que explota o te exploto yo!",
    "¡Vale cuatro al final! Que esta mano sella tu destino.",
    "Vale cuatro con 7 de oro, brillando como estrella en la noche.",
    "Quiero vale cuatro, mi amor, que por vos apuesto el universo.",
    "Vale cuatro serio, che, que cuatro puntos curan cualquier herida.",
    "¡Vale cuatro y un chiste! ¿Por qué vale cuatro? Porque tres es para ñoquis.",
    "Vale cuatro pampeano, tormenta que arrasa con tu defensa.",
    "Quiero vale cuatro, como el grito de independencia en la historia.",
    "Vale cuatro y un mate dulce, endulzando la victoria amarga.",
    "¡Vale cuatro, espada lista! El filo que corta dudas y perdedores.",
    "Vale cuatro cómico: con tres 4, pero alma de basto supremo.",
    "Quiero vale cuatro, que el retruco fue el prólogo, esto el fin.",
    "Vale cuatro nostálgico: en la pulpería se cerraba así la apuesta.",
    "¡Vale cuatro al revés! Te invierto la suerte como un maleficio.",
    "Vale cuatro y un abrazo fatal, apretando hasta el último punto.",
    "Quiero vale cuatro, boludo, que la gloria no espera a los tibios.",
    "Vale cuatro épico: como el cruce de los Andes, imparable.",
    "¡Vale cuatro con flor! Que cuatro flores perfuman la victoria.",
    "Vale cuatro agresivo: todo o revoleá, no hay término medio.",
    "Quiero vale cuatro, mi reina, que por amor subo al infinito.",
    "Vale cuatro y un tango final, dramático y triunfal al compás.",
    "¡Vale cuatro al cielo! Que Dios bendice esta mano audaz.",
    "Vale cuatro filosófico: el riesgo es la vida, cuatro es la eternidad.",
    "Quiero vale cuatro final, che, que esta mesa es mía para siempre.",
];
